spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    jpa:
      hibernate:
        ddl-auto: validate

server:
  error:
    include-message: always
